### ISSUE TITLE
How to use outlined icons

### ISSUE THREAD

**Issue by loic-roux-404** [marella/material-icons#10]
I have this line 
  `<i class="material-icons-outlined shopping-cart">shopping_cart</i>`
i also try 
  `<i class="material-icons shopping-cart">shopping_cart_outline</i>`
(dont pay attention to the shopping cart class, just for positionning)

Thanks for help !

**Comment by froston** [comment]
@loic-roux-404 
Having exactly the same issue!
Is there a solution for this?

**Comment by loic-roux-404** [comment]
Wow sorry it's been a long time, i don't even remember if i figured this.
I will try to find a solution by looking the project concerned.

**Comment by marella** [comment]
Sorry for the delay. Added new fonts and released a new version. Please update package and try again.

To display outlined, round, sharp and two tone icons, use:

```html
<span class="material-icons-outlined">home</span>
<span class="material-icons-round">home</span>
<span class="material-icons-sharp">home</span>
<span class="material-icons-two-tone">home</span>
```
