### ISSUE TITLE
Icon request: Sigh-In, Sign-Out icons

### ISSUE THREAD

**Issue by pavlikxor** [marella/material-icons#11]
It would be great to have sign-in, sign-out icons here.

**Comment by garbinmarcelo** [comment]
any news?

**Comment by marella** [comment]
Hi, new icons are not created on this repo. It only contains the icon font and required css for self hosting the icons.
From the available icons, [`login` icon](https://material.io/resources/icons/?icon=login&style=baseline) looks close to what you want:
```html
<span class="material-icons">login</span>
```
If you need more icons please try requesting on the [official repo](https://github.com/google/material-design-icons/issues).
