### ISSUE TITLE
Google lighthouse complains about font-display property

### ISSUE THREAD

**Issue by majid-1xinternet** [marella/material-icons#12]
> Ensure text remains visible during webfont load
Leverage the font-display CSS feature to ensure text is user-visible while webfonts are loading.

**Comment by marella** [comment]
Recently `font-display: block;` has been added in #21. I think `block` is better than `swap` for icon fonts as you don't want to see ligatures while font is loading. If you are using Sass, it can be changed using the variable `$material-icons-font-display`.
