### ISSUE TITLE
Help with mixins, icons not showing

### ISSUE THREAD

**Issue by JorgeSibrian14** [marella/material-icons#14]
I'm usign laravel 6 that work with webpack, i do this imports on app.scss:
//material-icons
$material-icons-font-path: '~material-icons/iconfont/';
@import '~material-icons/iconfont/material-icons.scss';
@import '~material-icons/iconfont/codepoints.scss';
@import '~material-icons/iconfont/mixins.scss';
@import '~material-icons/iconfont/variables.scss';
@import '~material-icons/css/material-icons.scss';
I add more imports than you recomend. 
And then i use this to put an icon in a button, just for trying:
![image](https://user-images.githubusercontent.com/56272944/82198027-f3ce2800-98b8-11ea-85a6-6d1e54b95af3.png)
I run: npm run dev(and i use too: npm run watch), and reload deleting cache from browser and i get this:
![image](https://user-images.githubusercontent.com/56272944/82198216-3bed4a80-98b9-11ea-8ca9-17b82577126d.png)
The material icons when i use the span tag is working well, but when i use the mixins that happens. Can you help me please?

**Comment by marella** [comment]
Sorry for the late response. You might be missing the `.material-icons` class. You can add it to the button class but it is not recommended:
```scss
.btn-secondary:before {
  @extend .material-icons;
}
```
It is better to display the icon using a separate element instead of modifying a common class:
```html
<button class="btn-secondary"><span class="material-icons">face</span>...</button>
```
