### ISSUE TITLE
No new icons?

### ISSUE THREAD

**Issue by voltuer** [marella/material-icons#15]
Hi, I'm trying to use [home_repair_service](https://material.io/resources/icons/?icon=home_repair_service&style=baseline) but it doesn't show. Are there any plans to update the library to the latest icons?

**Comment by AndrewDavis** [comment]
https://github.com/google/material-design-icons/issues/798#issuecomment-538663216
https://github.com/jossef/material-design-icons-iconfont
https://jossef.github.io/material-design-icons-iconfont/

**Comment by marella** [comment]
Sorry for the delay. Added new fonts and released a new version. Please see https://github.com/marella/material-icons/releases
