### ISSUE TITLE
no_accounts is not available

### ISSUE THREAD

**Issue by cmglez10** [marella/material-icons#23]
I miss the icon no_accounts (or mi-no-accounts)

It is available in material icons font from google: https://fonts.google.com/icons?selected=Material+Icons:no_accounts

**Comment by marella** [comment]
The following works in the latest version:
```html
<span class="material-icons">no_accounts</span>
```
Are you using CSS classes `<span class="mi mi-no-accounts"></span>`? Codepoints haven't been updated so new icons won't be available yet with this method.

**Comment by cmglez10** [comment]
Yes I was refering to the CSS classes, sorry about the missunderstunding. When do you estimate the codepoints will be available?

Thanks!

**Comment by marella** [comment]
I will try to update them next week. Google hasn't updated codepoints in their main repo so I will have to find another source.

**Comment by marella** [comment]
Updated codepoints and CSS classes for new icons. Please update to the [latest version](https://github.com/marella/material-icons/releases/tag/v0.6.1) and try again.

**Comment by cmglez10** [comment]
Wow. You are fast cowboy! 

Thank you very much!
