### ISSUE TITLE
Missing icons (login, logout, policy, push_pin, query_states, local_fire_department)

### ISSUE THREAD

**Issue by phinephate** [marella/material-icons#25]
First:
Thanks for this project. It really helps a lot !

Issue:
I noticed that some icons are missing (login, logout, policy, push_pin, query_states and local_fire_department).

There are available in material icons font from google: 
https://fonts.google.com/icons?selected=Material+Icons:login
https://fonts.google.com/icons?selected=Material+Icons:logout
https://fonts.google.com/icons?selected=Material+Icons:policy
https://fonts.google.com/icons?selected=Material+Icons:push_pin
https://fonts.google.com/icons?selected=Material+Icons:query_stats
https://fonts.google.com/icons?selected=Material+Icons:local_fire_department

**Comment by marella** [comment]
Are you using the [latest version](https://github.com/marella/material-icons/releases)? I'm seeing all of them on the [demo page](https://marella.github.io/material-icons/demo/).

**Comment by phinephate** [comment]
Of course not.
Thx for answering and sry for wasting your time.
