### ISSUE TITLE
Missing icon: shortcut

### ISSUE THREAD

**Issue by roushan** [marella/material-icons#27]
Hi there!

Just wanted to let you know that there is icon which I can see in the [demo](https://marella.me/material-icons/demo/) , but is missing in the files (I don't see it in the scss), and respectively can't be used. The icon is shortcut.

Cheers!

**Comment by marella** [comment]
Hi, are you using ligatures or CSS classes to display icon?
If you are using ligatures, you can directly use `<span class="material-icons">shortcut</span>` and the icon name need not to be present in CSS/SCSS.
If you are using CSS classes, you can use `<span class="material-icons mi-shortcut"></span>` which is declared in https://github.com/marella/material-icons/blob/383d560b81552793e6f0033cc8ba468f846f6622/css/material-icons.css#L6434
Also make sure you are using the [latest version](https://github.com/marella/material-icons/releases).

**Comment by roushan** [comment]
Thank you! It's on my side then. Thanks a lot for the hints where and what to look for.
