### ISSUE TITLE
CSS usage doesn't work

### ISSUE THREAD

**Issue by Waysti** [marella/material-icons#29]
The usage via css is currently not working.
The icons only will be displayed if I add the following (from iconfont folder) to my own css:

@font-face {
  font-family: "Material Icons";
  font-style: normal;
  font-weight: 400;
  font-display: block;
  src: url("~material-icons/iconfont/material-icons.woff2") format("woff2"), url("~material-icons/iconfont/material-icons.woff") format("woff");
}
.material-icons {
  font-family: "Material Icons";
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  line-height: 1;
  letter-spacing: normal;
  text-transform: none;
  display: inline-block;
  white-space: nowrap;
  word-wrap: normal;
  direction: ltr;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-rendering: optimizeLegibility;
  font-feature-settings: "liga";
}

this I have to do for each style (outlined, etc.)

is this the wanted behaviour? then it should be mentioned in the docs.

**Comment by marella** [comment]
The files mentioned in the [main readme](https://github.com/marella/material-icons#usage) should also be imported in addition to the files mentioned in the [css readme](https://github.com/marella/material-icons/tree/main/css#readme):

```js
import 'material-icons/iconfont/material-icons.css'; // Imports font files for all styles
import 'material-icons/css/material-icons.css'; // Allows usage of CSS classes
```

I will update the readme to better reflect this.

**Comment by Waysti** [comment]
thx for your reply. after adding all imports like in your post everything works as expected.
from the current readme i couldn't read out that I have to import the material-icons.css from iconfont.

but the update of the readme would surely help there.
thx.
