### ISSUE TITLE
Support for Material Symbols

### ISSUE THREAD

**Issue by boywithkeyboard** [marella/material-icons#31]
The team at Google Fonts recently released [**Material Symbols**](https://fonts.google.com/icons), a new, much more customizable version of Material Icons.

It would be amazing if you could add support for them, by adding a second workflow looking for the latest version of Material Symbols and a separate `material-symbols.css` for them.

**Comment by marella** [comment]
Thanks for letting me know. I added them to a separate package [`material-symbols`](https://www.npmjs.com/package/material-symbols) in a separate repo [marella/material-symbols](https://github.com/marella/material-symbols).
Please see [README](https://github.com/marella/material-symbols/tree/main/material-symbols#readme) for more info.

**Comment by boywithkeyboard** [comment]
That's amazing, thank you so much @marella! I'll try it out asap.
