### ISSUE TITLE
Publish codepoints/versions.json?

### ISSUE THREAD

**Issue by neodescis** [marella/material-icons#32]
I'm interested in creating an icon picker using this package, but I'd really like to have a list of icons available so I don't need to copy the list and keep it updated. Would it be possible to publish codepoints.json and/or versions.json to npm?

**Comment by marella** [comment]
I can include `_data/versions.json` in the package. `codepoints.json` is not reliable to get list of available icons as it is generated from font files and contains some extra ligatures which are not valid icons.

**Comment by neodescis** [comment]
OK, I thought as much from one of the commits. Publishing versions.json would be very useful!

**Comment by marella** [comment]
Published in the latest release 1.11.0

**Comment by neodescis** [comment]
I just completed my icon picker based on this data, and it's very nice. Thanks again!
