### ISSUE TITLE
A lot of icons are not displayable

### ISSUE THREAD

**Issue by dennis-f** [marella/material-icons#33]
Following Icons are inside of `_codepoints.scss` but they are not displayable:

- 'battery_20',
- 'battery_30',
- 'battery_50',
- 'battery_60',
- 'battery_80',
- 'battery_90',
- 'battery_charging_20',
- 'battery_charging_30',
- 'battery_charging_50',
- 'battery_charging_60',
- 'battery_charging_80',
- 'battery_charging_90',
- 'copy',
- 'cut',
- 'paste',
- 'signal_cellular_0_bar',
- 'signal_cellular_1_bar',
- 'signal_cellular_2_bar',
- 'signal_cellular_3_bar',
- 'signal_cellular_4_bar',
- 'signal_cellular_connected_no_internet_1_bar',
- 'signal_cellular_connected_no_internet_2_bar',
- 'signal_cellular_connected_no_internet_3_bar',
- 'signal_wifi_1_bar',
- 'signal_wifi_1_bar_lock',
- 'signal_wifi_2_bar',
- 'signal_wifi_2_bar_lock',
- 'signal_wifi_3_bar',
- 'signal_wifi_3_bar_lock',
- 'signal_wifi_4_bar',
- 'signal_wifi_connected_no_internet_0',
- 'signal_wifi_connected_no_internet_1',
- 'signal_wifi_connected_no_internet_2',
- 'signal_wifi_connected_no_internet_3',
- 'signal_wifi_statusbar_1_bar',
- 'signal_wifi_statusbar_2_bar',
- 'signal_wifi_statusbar_3_bar',
- 'signal_wifi_statusbar_connected_no_internet',
- 'signal_wifi_statusbar_connected_no_internet_1',
- 'signal_wifi_statusbar_connected_no_internet_2',
- 'signal_wifi_statusbar_connected_no_internet_3',
- 'signal_wifi_statusbar_not_connected',

Thanks for your work! It seems to be the only way to use material icons via npm 👍

**Comment by dennis-f** [comment]
Additionally the following icons do exist in `version.json` but not in `_codepoints.scss`

- add_call
- adobe
- airplanemode_off
- airplanemode_on
- amp_stories
- apple
- assistant_navigation
- battery_20
- battery_30
- battery_50
- battery_60
- battery_80
- battery_90
- battery_charging_20
- battery_charging_30
- battery_charging_50
- battery_charging_60
- battery_charging_80
- battery_charging_90
- block_flipped
- bookmark_outline
- cloudy_snowing
- confirmation_num
- copy
- cut
- directions_ferry
- directions_train
- discord
- dnd_forwardslash
- drive_file_move_outline
- eco
- emoji_flags
- enhance_photo_translate
- exposure_minus_1
- exposure_minus_2
- face_unlock
- facebook
- favorite_outline
- filter_list_alt
- fire_hydrant
- flourescent
- foggy
- format_underline
- goat
- highlight_remove
- home_filled
- info_outline
- invert_colors_on
- keyboard_command
- keyboard_control
- keyboard_option
- label_important_outline
- label_outline
- leave_bags_at_home
- lightbulb_outline
- local_attraction
- local_print_shop
- local_restaurant
- location_history
- location_pin
- lock_outline
- messenger
- messenger_outline
- motorcycle
- multitrack_audio
- my_library_add
- my_library_books
- my_library_music
- no_meals_ouline
- notifications_on
- now_wallpaper
- now_widgets
- outbond
- outgoing_mail
- panorama_fisheye
- paste
- paypal
- perm_contact_cal
- perm_device_info
- pie_chart_outlined
- play_circle_fill
- quick_contacts_dialer
- quick_contacts_mail
- quora
- radio_button_off
- radio_button_on
- reddit
- settings_display
- share_arrival_time
- shopify
- signal_cellular_1_bar
- signal_cellular_2_bar
- signal_cellular_3_bar
- signal_cellular_connected_no_internet_1_bar
- signal_cellular_connected_no_internet_2_bar
- signal_cellular_connected_no_internet_3_bar
- signal_wifi_1_bar
- signal_wifi_1_bar_lock
- signal_wifi_2_bar
- signal_wifi_2_bar_lock
- signal_wifi_3_bar
- signal_wifi_3_bar_lock
- signal_wifi_connected_no_internet_0
- signal_wifi_connected_no_internet_1
- signal_wifi_connected_no_internet_2
- signal_wifi_connected_no_internet_3
- signal_wifi_statusbar_1_bar
- signal_wifi_statusbar_2_bar
- signal_wifi_statusbar_3_bar
- signal_wifi_statusbar_connected_no_internet
- signal_wifi_statusbar_connected_no_internet_1
- signal_wifi_statusbar_connected_no_internet_2
- signal_wifi_statusbar_connected_no_internet_3
- signal_wifi_statusbar_not_connected
- snapchat
- snowing
- sunny
- sunny_snowing
- swap_vert_circle
- system_update_tv
- telegram
- tiktok
- trending_neutral
- video_chat
- video_collection
- view_comfortable
- volume_down_alt
- wallet_giftcard
- wallet_membership
- wallet_travel
- wb_twighlight
- wechat
- wifi_calling_1
- wifi_calling_2
- wifi_tethering_error_rounded
- woo_commerce
- wordpress
- workspaces_filled
- workspaces_outline

**Comment by marella** [comment]
> Following Icons are inside of `_codepoints.scss` but they are not displayable:

`_codepoints.scss` is generated from font files and they contain some extra ligatures which are not valid icons.

> Additionally the following icons do exist in version.json but not in _codepoints.scss

It is the other way around, some icons are present in `_codepoints.scss` but not in `versions.json`. `versions.json` is generated from the API used on [fonts site](https://fonts.google.com/icons). When icons are removed from the fonts site, Google doesn't remove them from the font files for backward compatibility. So I'm also not removing them from `_codepoints.scss`.

So only icons listed on [fonts site](https://fonts.google.com/icons) or [demo page](https://marella.github.io/material-icons/demo/) or `versions.json` should be used. Other extra icons present in `_codepoints.scss` might no longer be supported or are invalid icons.

**Comment by dennis-f** [comment]
Great! Thanks for your feedback 🙂
