### ISSUE TITLE
 The new icons from version 1.11.6 are not available when using

### ISSUE THREAD

**Issue by adacostac** [marella/material-icons#34]
The project that currently makes use of the icons has been updated to the latest version, but when trying to use the icons they are not available

**Comment by marella** [comment]
Are you getting any error? Can you please provide more details like the build tool (Webpack etc.), framework (React etc.) you are using and how you are importing the icons.
Also was it working with an older version (1.11.5)? A new version (1.11.7) is released. Can you please try with the latest version and let me know if you are still facing issues.

**Comment by adacostac** [comment]
Hi, I am implementing the icons in Angular 11.2.14. The inconvenience found in version 1.11.6 is that the new icons only have one style and when trying to use them they just didn't appear, it didn't throw an error or anything, on the other hand in our project we used the outlinet icons. We have tested the new version 1.11.7 today and all are now working properly.
