### ISSUE TITLE
Outlined icon for label_important is incorrect

### ISSUE THREAD

**Issue by kerim1510** [marella/material-icons#40]
The outlined icon for label_important is filled instead of outlined

**Comment by marella** [comment]
Please report icon specific issues on [official repo](https://github.com/google/material-design-icons/issues).

[Material Symbols](https://www.npmjs.com/package/material-symbols) seems to have the correct one [here](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:label_important:FILL@0;wght@400;GRAD@0;opsz@48).
