### ISSUE TITLE
Fast copy icons element?

### ISSUE THREAD

**Issue by luoyangwei** [marella/material-icons#41]
![image](https://user-images.githubusercontent.com/31927848/213403920-fece6dc9-b7dc-4df5-bf90-e34cbbd15b90.png)

I often use icon sets to look up the icons I want when developing, but it is very inconvenient, and I need to memorize the icon names every time. It would be great if you could add a click to copy directly, I think that would be very convenient.

![image](https://user-images.githubusercontent.com/31927848/213404886-2d460ef5-385b-4479-a55c-b91f2d83d065.png)

**Comment by marella** [comment]
Sorry for the late response. As a workaround you can double click on the icon name which selects the entire name text and then copy using `ctrl/cmd + c`.
If you are using TypeScript, you can use `MaterialIcon` type which can help autocomplete the icon names.

I will look into adding the copy functionality when I get time.

**Comment by luoyangwei** [comment]
Double click the icon to copy can also solve my problem, thanks.
