### ISSUE TITLE
Monitoring icon is missing

### ISSUE THREAD

**Issue by semihbas** [marella/material-icons#45]
Hi, thanks for this. I've just noticed the monitoring icon is missing. Would it be possible to add it?

![image](https://user-images.githubusercontent.com/10476252/229777974-2ba987e5-c51f-43d7-9342-8cc98d50b515.png)

**Comment by marella** [comment]
Hi, `monitoring` icon is available in Material Symbols. This package is for Material Icons.

For Material Symbols, use [material-symbols](https://www.npmjs.com/package/material-symbols) package.

**Comment by semihbas** [comment]
Perfect! Thank you!
