### ISSUE TITLE
Outdated font files

### ISSUE THREAD

**Issue by cre8** [marella/material-icons#47]
The latest version of this is 9 months old. The google repo is only 8 months old, so some icons seem to be missing (like verified).

With the mentioning in the readme they seem to also another source: https://github.com/google/material-design-icons/tree/master/variablefont

**Comment by marella** [comment]
The link posted above is for Material Symbols which are available in [marella/material-symbols](https://github.com/marella/material-symbols/tree/main/material-symbols) repo. This repo is for Material Icons.

I just manually checked the font files in this repo with the font files on [Google Fonts](https://fonts.google.com/icons?icon.set=Material+Icons) and they are same which means font files haven't changed for Material Icons in the past 9 months.

`verified` icon is available in this repo (search in [demo](https://marella.me/material-icons/demo/)). If you find any other icon missing in this repo but present on Google Fonts site please let me know.
